### ISSUE TITLE
[BUG] No module named 'dbus'

### ISSUE THREAD

**Issue by iandark** [SwagLyrics/SwagLyrics-For-Spotify#2860]
When i call swaglyrics CLI or web i got error message

```
~$ swaglyrics -c 
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/swaglyrics", line 33, in <module>
    sys.exit(load_entry_point('swaglyrics', 'console_scripts', 'swaglyrics')())
  File "/home/USERIAM/Dev/SwagLyrics-For-Spotify/swaglyrics/__main__.py", line 121, in main
    show_cli(make_issue)
  File "/home/USERIAM/Dev/SwagLyrics-For-Spotify/swaglyrics/__main__.py", line 68, in show_cli
    song, artist = spotify.current()  # get currently playing song, artist
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/SwSpotify/spotify.py", line 136, in current
    return get_info_linux()
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/SwSpotify/spotify.py", line 55, in get_info_linux
    import dbus
ModuleNotFoundError: No module named 'dbus'
```
I alreay installed python-dbus
`sudo apt-get install python-dbus`
`sudo apt install  python3-dbus`

**Comment by aadibajpai** [comment]
can you give me some info about what os you're on? That might help pinpoint which dbus you need. Also see if `pip install dbus-python` does the trick

**Comment by iandark** [comment]
> can you give me some info about what os you're on? That might help pinpoint which dbus you need. Also see if `pip install dbus-python` does the trick

I'm using Ubuntu 20.04.

```
~$ pip install dbus-python                
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: dbus-python in /usr/lib/python3/dist-packages (1.2.16)
```
