### ISSUE TITLE
[BUG] Cant install application

### ISSUE THREAD

**Issue by akash-258** [SwagLyrics/SwagLyrics-For-Spotify#2893]
**Describe the bug**
After doing `pip install swaglyrics`, I get this error in red colour in terminal : 

`ERROR: swspotify 1.2.3 has requirement flask<3.0.0,>=2.0.1, but you'll have flask 1.1.2 which is incompatible.
`
And when executing `swaglyrics -c`, getting these errors 

```
Traceback (most recent call last):
  File "/home/akash/.local/bin/swaglyrics", line 5, in <module>
    from swaglyrics.__main__ import main
  File "/home/akash/.local/lib/python3.8/site-packages/swaglyrics/__main__.py", line 11, in <module>
    from swaglyrics.tab import app
  File "/home/akash/.local/lib/python3.8/site-packages/swaglyrics/tab.py", line 4, in <module>
    from flask import Flask, render_template
  File "/home/akash/.local/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/home/akash/.local/lib/python3.8/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/home/akash/.local/lib/python3.8/site-packages/itsdangerous/__init__.py)
```

**Desktop :**
 - OS: Linux Mint 20.3 x86_64 based on Ubuntu 20.04
 - Kernel: 5.4.0-104-generic
 - Version 1.2.2

**Comment by aadibajpai** [comment]
I am not sure what is the issue with the dependency resolution here but I will try to get this figured out soon.

**Comment by b33-stinger** [comment]
worth mentioning that itsdangerous removed the json module at some point. So installing `itsdangerous<2.1` should fix it

`python3 -m pip install "itsdangerous<2.1"`

~someone gotta rewrite this project :pain:~
https://github.com/raitonoberu/sptlrx seems to be a newer more active project

**Comment by aadibajpai** [comment]
> worth mentioning that itsdangerous removed the json module at some point. So installing `itsdangerous<2.1` should fix it
> 
> `python3 -m pip install "itsdangerous<2.1"`
> 
> ~someone gotta rewrite this project :pain:~ https://github.com/raitonoberu/sptlrx seems to be a newer more active project

woah that's cool to see someone else made a similar application. I should really get around to fixing this
