### ISSUE TITLE
[BUG] Your title here.

### ISSUE THREAD

**Issue by timocarnill** [SwagLyrics/SwagLyrics-For-Spotify#2906]
**Describe the bug**
Python import error when running:
ImportError: cannot import name 'escape' from 'jinja2' (C:\Users\timoc\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\__init__.py)

OS: Windows 11

**Comment by michaelmior** [comment]
I'm seeing this on macOS too, although it would help to add a proper title to the issue.

**Comment by Azfrd08** [comment]
Im getting the same error : 

_Traceback (most recent call last):
  File "/home/azfrd/.local/bin/swaglyrics", line 5, in <module>
    from swaglyrics.__main__ import main
  File "/home/azfrd/.local/lib/python3.10/site-packages/swaglyrics/__main__.py", line 11, in <module>
    from swaglyrics.tab import app
  File "/home/azfrd/.local/lib/python3.10/site-packages/swaglyrics/tab.py", line 4, in <module>
    from flask import Flask, render_template
  File "/home/azfrd/.local/lib/python3.10/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/home/azfrd/.local/lib/python3.10/site-packages/jinja2/__init__.py)_

**Comment by korosig** [comment]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\swaglyrics.exe\__main__.py", line 4, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\swaglyrics\__main__.py", line 11, in <module>
    from swaglyrics.tab import app
  File "C:\ProgramData\Anaconda3\lib\site-packages\swaglyrics\tab.py", line 4, in <module>
    from flask import Flask, render_template
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (C:\Users\user\AppData\Roaming\Python\Python39\site-packages\jinja2\__init__.py)

**Comment by aadibajpai** [comment]
sorry for the delay all, been a bit busy with school and work. Will get to this soon

**Comment by bmrussell** [comment]
Found a workaround:

```bash
pip uninstall flask
pip install flask
```

**Comment by T0RNATO** [comment]
Workaround doesn't work for me, getting a ton of runtime errors:
> RuntimeError: Not running with the Werkzeug Server
